FROM google/cloud-sdk:212.0.0-alpine

RUN cd /usr/local/bin && curl -sL  https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip > /tmp/terraform.zip && unzip /tmp/terraform.zip && rm /tmp/terraform.zip


